### ISSUE TITLE
Compiling error in Mac M1

### ISSUE THREAD

**Issue by alcalawil** [benediktwerner/lichess-docker#2]
Hi, I am having the following issue when running `docker build --tag lichess .` I guess is because of the ARM processor cause I had issues with other docker images but not sure. 

`#10 2.495 E: Unable to locate package mongodb-org`

Any Ideas?
Thanks!

**Comment by benediktwerner** [comment]
I can't really help much with that. Is it possible to run Docker under x86 emulation? If not, you will have to figure out how to install mongo on Debian with ARM and modify the Dockerfile accordingly. I wouldn't be surprised if some other things later on won't work either. It might be a good idea to just comment out everything starting from the mongo installation in the Dockerfile, run it, and then do every step manually inside the container so that you can try out stuff quickly.

You definitely also should read the notes here: https://github.com/lichess-org/lila/wiki/Lichess-Development-Onboarding-(macOS)
